### ISSUE TITLE
Multiple undo within a Batch proceeds in incorrect order

### ISSUE THREAD

**Issue by kalisohn** [WildGums/Orc.Memento#1]
### Steps to reproduce

1. BeginBatch()
2. Change the value of a property multiple times
3. EndBatch()
4. UndoBatch() 

The following unit test will fail, because the Undo() method processes the _actions List in the wrong order:
`
public void UndoBatchesTest()
{
            Item item = new Item();
            var mementoService = new MementoService();
            mementoService.RegisterObject(item);
            string originalNumber = item.Nr;

            mementoService.BeginBatch();

            item.Nr = "1000";
            item.Nr = "100";
            item.Nr = "10";

            IMementoBatch mementoBatch = mementoService.EndBatch();
            mementoBatch.Undo();
            Assert.Equals(originalNumber, item.Nr); //fails, the value is 100.
}`
      

Platform: x64 win7
.NET version: 4.5.2

### Expected behaviour
The value after undo() should be the original value when using Batches.

### Actual behaviour
The value after undo() is the value of the last step. 
The _actions List of Batch.cs should be either a Stack or it should be reversed.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting! Interested in doing a PR?

**Comment by GeertvanHorrik** [comment]
Assigning to @alexfdezsauco

**Comment by GeertvanHorrik** [comment]
Released 2.0.1
