### ISSUE TITLE
Does this support rolling back changes?

### ISSUE THREAD

**Issue by FutureTD** [WildGums/Orc.Memento#18]
Typically in my application I let the user edit the model/viewmodel and I have a cancel button in which they can roll back all changes made.  Does this library support this or is it easier just to clone the whole object and and use the original?

Also for my use case I typically only need one undo per property. So for example say I have string property called name, and I edit the name property twice does that create 2 undo actions for the property or does it just overwrite the latest undo for that property.

**Comment by GeertvanHorrik** [comment]
If you use `ModelBase` (or have your models implement `IEditableObject`) and decorate it with the `Model` attribute, the VM's will automatically revert for you.

The memento pattern is for already committed changes (e.g. list of history), where you can undo in batches (which you can define yourself).
