### ISSUE TITLE
CanUndo/CanRedo not observable

### ISSUE THREAD

**Issue by GreenKn1ght** [WildGums/Orc.Memento#24]
Im trying to disable Undo/Redo commands when CanUndo/CanRedo are false.
There is MementoService.Updated event, but CanUndo/CanRedo are always false when this event occurs. It is also not possible to know that an operation has been added or deleted by clean.

### Steps to reproduce
To be added

**Comment by GeertvanHorrik** [comment]
Good point. We don't actively use this lib at the moment, interested in doing a PR?

**Comment by GreenKn1ght** [comment]
Yes, I'll add some examples and fix this issue.

**Comment by GeertvanHorrik** [comment]
Got a user sending us code to fix this. Will create a PR on his behalf
